server:
  port: 9191


app:
  config:
    # 接口版本
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'


spring:
#  数据库连接信息
  datasource:
    username: root
    password: 690501LJK
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

# redis连接信息 默认没有配置密码
  redis:
    port: 6379
    host: localhost

# myabtis配置
mybatis:
  #扫描Mapper.xml文件 sql文件所在处
  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location: classpath:/mybatis-config
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


